### PR TITLE
Added Windows Jenkins link.

### PR DESCRIPTION
**Pull request by uwuplant**
Hosting Jenkins on my PC, commits will be automatically built. (hopefully)

### CODE REVIEW

**Comment by cthpw103** [comment]
put this on a vps or something

**Comment by uwuplant** [comment]
nah, my PC's on 24/7, plus I don't have a vps to use for it anyway

**Comment by cthpw103** [comment]
some guy who hates fun might ddos it

**Comment by uwuplant** [comment]
don't give them ideas :^)

**Comment by nevercast** [comment]
Can we consider using public services like www.appveyor.com and travis-ci.com. More reliable, easier for everyone to maintain, free for open source, keeps everything related to the build system in one place (this repo)

**Comment by uwuplant** [comment]
ah, okay

just wanted to help with this :p

**Pull request closed without merging**
