### PR TITLE
tested & added .exe

### PR DESCRIPTION
**Pull request by Jabrils**
the .exe has been tested, & it works. Also added instructions to the readme. MERGE THIS CARY!

### CODE REVIEW

**Comment by DeflatedPickle** [comment]
It works... for you. But you didn't specify what this was compiled on. It's likely someone running this on a different processor or an older version of Windows couldn't run this, and they might not know since they have no build information to reference.

Also, it's quite bad practice to add an executable to the repo's source. Releases exist for this reason. It's also a better idea to use a CI like Travis to build your binaries, as they're usually available for more operating systems and can be used with a very minimal config file.

**Comment by Jabrils** [comment]
🤷 good to know. Admittedly, I have not tested it on any other hardware so your point makes sense. I don't have time to learn how to build CI binaries, so I will close this pull.

**Comment by cthpw103** [comment]
still open

**Comment by cthpw103** [comment]
btw: what about the people with 32 bit cpus/oses? have you built the executable in 32 bits?

**Pull request closed without merging**
