### PR TITLE
make requirements.txt file

### PR DESCRIPTION
**Pull request by cthpw103**
make sure i dont include any builtin library

### CODE REVIEW

**Comment by carykh** [comment]
i think it's good to go. Thanks!

**Comment by carykh** [comment]
oh wait, I think you also need FFmpeg for it to work, but that's not a Python library... my code just starts a subprocess and runs ffmpeg.

**Comment by ichbineinNerd** [comment]
that should probably be mentioned in the readme

**Comment by carykh** [comment]
true, I'll add it there.

**Pull request merged**
