### PR TITLE
Added dependency versions

### PR DESCRIPTION
**Pull request by ClashLuke**
* Removes bugs created through wrong pip (pip2/pip3)
* Automatically updates pip to the latest version, for lazy users

### CODE REVIEW

**Comment by Bottersnike** [comment]
Pinning dependency versions is usually a bad idea. Is it possible to change these into `>`s instead of `==`s, and trace back features to work out the actual required versions? Having pinned versions like this not only means patches from libraries don't get updated, but it will also cause dependency conflicts with other things installed on the system.

**Comment by ClashLuke** [comment]
No.
Seriously, no idea, but I suspect that Pip3 installs a higher version than Pip2 does.

**Comment by Bottersnike** [comment]
Right, so, you should never include pip as a dependancy of a project if it isn't. This code will run perfectly find without pip. Ignoring that glaring problem, the problem of version pinning is the main issue right now.

**Comment by ClashLuke** [comment]
Well, it was on purpose. I explicitly wanted to force a user to use the latest python2 pip, looking further into it, pip2 and pip3 appear to be on the same version, so yes, it is unnecessary.
About version pinning, pretty sure it'd be fine just to use >= instead of ==, but for safety reasons I'd leave it at numpy the way it is.

**Comment by Bottersnike** [comment]
You seem to greatly misunderstand the point of a requirements file. Hint: It's in the name. Is pip a requirement of jumpcutter? No. Should it be, therefore, in the requirements file? No. For `==`, the point of a requirements file is to tell python "If you have this version, it'll work." If something, say, worked with both version 0.3 and 0.4, telling python "You need 0.4" is just **wrong**, instead you should say "It works with 0.3 or 0.4" so that if something else **needs** 0.3, python knows that your program will still run without having to break the other program.

**Comment by ClashLuke** [comment]
I am fully aware of that, but I am not interested in testing all versions to see what it works with. To allow the usage of this code across platforms and machines, it is necessary to specify the versions. A bash script installing and upgrating them would technically work aswell.

**Comment by Bottersnike** [comment]
If you can't be bothered to make a proper PR, why make one? At the very least pip **must** be removed before this file can serve its proper purpose. The fact that you left things like Pillow in there when its clearly not used at all in the code is another indication you didn't really bother.

**Pull request closed without merging**
