### PR TITLE
Create AIO-installer

### PR DESCRIPTION
**Pull request by ascpixel**
Automatically installs the dependencies with pip (easy-install).

### CODE REVIEW

**Comment by cthpw103** [comment]
theres a requirements.txt file

**Comment by kbartek05** [comment]
Yeah, but this installs it automatically! Perfect for a procrastinator like me :D

**Comment by kbartek05** [comment]
_(it would hurt to add this...)_

**Comment by balsoft** [comment]
Just a heads-up: when you screw up, do `git commit --amend; git push --force` so that there's just one commit instead of two.

**Comment by kbartek05** [comment]
I used the web app, I had a problem with permissions (never had an error like this before, and I never used GitHub on the web for committing)

**Comment by noellekiq** [comment]
how hard is it to run `python -m pip install -R requirements.txt`

**Comment by balsoft** [comment]
> how hard is it to run `python -m pip install -R requirements.txt`

Pretty hard if you think about it. You need to have python and pip installed, and also in this case ffmpeg. (Although this script doesn't help a single bit)

**Comment by kbartek05** [comment]
Yeah, I just realized this is useless atm. Oh well, maybe this will be helpful if I add installing FFmpeg to the batch file, maybe then this will be useful for some kind of installer.

**Comment by Bottersnike** [comment]
Looking at this, if you're going to write a script to do it automatically which, by the way, is pretty bad practice, you should at least have tha script use `requirements.txt`. Said file is designed for this exact puprose, allows version pinning, etc. Furthermore, your method of "locating" python when it's not found it to.. overwrite `%PATH%`?!

**Comment by kbartek05** [comment]
I'm doing a complete rewrite right now, I made this script in the middle of the night (for me) so I was tired, sorry.

**Comment by Bottersnike** [comment]
Given that `pip install -r requirements.txt` exists as a command, is this script even needed though?

**Comment by kbartek05** [comment]
This file will also install ffmpeg (which is missing an installer for windows) so that will help the non-tech savvy users. The python modules are an added bonus. Oh, and I will also make python auto-download if you don't have it. But cary says it's in Python2, but some user pointed out some Python 3 syntaxes? What python version I'm supposed to download? (i'm using certutil to download, because it is still supported, unlike bitsadmin.)

**Comment by Bottersnike** [comment]
Always download the latest version of python3. It's currently https://www.python.org/ftp/python/3.7.3/python-3.7.3.exe but that link changes regularly. At this point it feels like you'd be much better bundling something like a nullsoft installer instead of a batch script.

**Comment by kbartek05** [comment]
Yeah, but I have more experience with batch. And it will output the same result.

**Comment by kbartek05** [comment]
Alright, I made the AIO installer. Uploaded this as a commit because the previous comments would not make sense.

**Comment by CoolOppo** [comment]
> Just a heads-up: when you screw up, do `git commit --amend; git push --force` so that there's just one commit instead of two.

It's almost always [better](http://weiqingtoh.github.io/force-with-lease/) to use `--force-with-lease`. ([Official Git docs](https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-force-with-lease))

**Comment by balsoft** [comment]
@CoolOppo Yeah, true. Doesn't matter that much in this case.

**Comment by rougetimelord** [comment]
Currently this only grabs the x32 build of ffmpeg. Additionally the link is to a specific version of ffmpeg which may change. These links might work better, [https://ffmpeg.zeranoe.com/builds/win32/static/ffmpeg-latest-win32-static.zip](url) and [https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip](url).

**Pull request closed without merging**
